name: Destroy Infrastructure Pipeline
on:
  workflow_dispatch:
jobs:
  destroy:
    name: Destroy Terraform infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: TerraFormTemplate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup TerraForm
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          #aws-access-key-id: ${{secrets.tf_aws_access_key_id}}
          #aws-secret-access-key: ${{secrets.tf_aws_secret_access_key}}
          role-to-assume: arn:aws:iam::578160920339:role/github-actions-oidc-role
          aws-region: ${{secrets.aws_region}}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve