name : Angular CI Pipeline
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DummyUI
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Use Node.js 18
        uses: actions/setup-node@v3 
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: DummyUI

      - name: Build Angular App
        run: ng build --configuration production
        working-directory: DummyUI
