name: Infrastructure CI Pipeline
on:
  workflow_run:
    workflows:
      - "Remote-Backend for Terraform State"
    types:
      - completed
permissions:
      id-token: write
      contents: read
    
jobs:
  terraform:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    name: Apply Terraform Templates
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TerraFormTemplate
    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          #aws-access-key-id: ${{secrets.tf_aws_access_key_id}}
          #aws-secret-access-key: ${{secrets.tf_aws_secret_access_key}}
          role-to-assume: arn:aws:iam::578160920339:role/github-actions-oidc-role
          aws-region: ${{secrets.aws_region}}

      - name: Terraform init
        run: terraform init -reconfigure
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan
      
      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: Wait for Outputs to be ready
        run: sleep 2

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install gh -y
    

      - name: Show Terraform Outputs
        run: |
          echo "============= TerraForm Outputs ============="
          terraform output -json
      #- name: Display selected Terraform Outputs
        #run: |
        #  echo "CloudDistribution Id: $(terraform output -raw angular_cloudfront_distribution_id)"
         # echo "API Gateway URL: $(terraform output -raw angular_base_api_url)"
          #echo "S3 Bucket name: $(terraform output -raw s3_bucket_name)"
          #echo "AWS Access Key for Angular CI/CD :"
          #terraform output -raw cicd_user_access_key_id
          #echo "AWS Secret Key for Angular CI/CD:"
          #terraform output -raw cicd_user_secret_access_key
          #echo "=============== Terraform Outputs ends ==============="

      - name: Extract Terraform Outputs
        id: extract
        run: |
          echo "bastion_host_ip=$(terraform output -raw dummy_bastion_host_ip)" >> $GITHUB_OUTPUT
          echo "bastion_host_instance_id=$(terraform output -raw dummy_bastion_host_id)" >> $GITHUB_OUTPUT

      - name: Download .pem file from S3
        id: download_pem
        run: |
          aws s3 cp s3://bastion-private-key.1981/dummy-bastion-key.pem dummy-bastion-key.pem
          chmod 400 dummy-bastion-key.pem

      - name: Decrypt Bastion Windows Password
        id: decrypt_pw
        run: |
          password=$(aws ec2 get-password-data \
          --instance-id ${{ steps.extract.outputs.bastion_host_instance_id }} \
          --priv-launch-key dummy-bastion-key.pem \
          --query 'PasswordData' \
          --output text)
          echo "password=$password" >> $GITHUB_OUTPUT

      - name: Show result (Debug Only)
        run: |
          echo "Bastion_IP:${{ steps.extract.outputs.bastion_host_ip }}"
          echo "Bastion_Password:${{ steps.decrypt_pw.outputs.password }}"

      - name: Export Terraform Outputs as GitHub Secrets
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          BASTION_IP: ${{steps.extract.outputs.bastion_host_ip}}
          BASTION_PASSWORD: ${{steps.decrypt_pw.outputs.password}}
        run: |
          echo "=======Exporting Terraform Outputs as GitHub Secrets======="
          cloud_front_id=$(terraform output -raw angular_cloudfront_distribution_id)
          api_url=$(terraform output -raw angular_base_api_url)
          s3_bucket_name=$(terraform output -raw s3_bucket_name)
          # cicd_access_key_id=$(terraform output -raw cicd_user_access_key_id)
          # cicd_secret_access_key=$(terraform output -raw cicd_user_secret_access_key)
          aws_region=$(terraform output -raw project_region)
          angular_cicd_user_role=$(terraform output -raw github_actions_role_arn)
          
          bastion_id=$BASTION_IP
          bastion_password=$BASTION_PASSWORD

          if [ -z "$bastion_id" ] || [ -z "$bastion_password" ];then
            echo "Cannot save to Secrets. Bastion IP or Bastion Password is empty"
            exit 1
          fi

          gh secret set CLOUD_DISTRIBUTION_ID -b "$cloud_front_id"
          gh secret set API_URL -b "$api_url"
          gh secret set S3_BUCKET_NAME -b "$s3_bucket_name"
          gh secret set AWS_REGION -b "$aws_region"
          # gh secret set AWS_ACCESS_KEY_ID -b "$cicd_access_key_id"
          # gh secret set AWS_SECRET_ACCESS_KEY -b "$cicd_secret_access_key"
          gh secret set ANGULAR_CICD_USER_ROLE -b "$angular_cicd_user_role"
          gh secret set BASTION_IP -b "$bastion_id"
          gh secret set BASTION_PASSWORD -b "$bastion_password"

          echo "======== GitHub Secrets updated successfully================"



