name: Remote-Backend for Terraform State
on:
  workflow_dispatch:

jobs:
  terraform:
    name: Apply terraform templates
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TerraFormTemplate/remote-backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform Template
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.tf_aws_access_key_id}}
          aws-secret-access-key: ${{secrets.tf_aws_secret_access_key}}
          aws-region: ${{secrets.aws_region}}
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
           
      - name: Terraform Apply
        run: terraform apply -auto-approve 

      - name: Terraform Outputs
        run: |
          echo "==========Terraform Outputs=========="
          terraform output -json
          echo "State S3 bucket:" $(terraform output -raw remote_state_bucket_name)
          echo "State Dynamodb Table Name : " $(terraform output -raw remote_state_lock_table)
